GET http://localhost:3001/todos

###
POST http://localhost:3001/todos/new
Content-Type: application/json

{
    "text": "Task 45",
    "description": "Soon to work on other things",
    "dueDate": "2023-02-28T23:59:59"
}

###
DELETE http://localhost:3001/todos/delete/


###
PUT http://localhost:3001/todos/complete/


###
PUT http://localhost:3001/todos/update/64027534404f2dd57fe27a88
Content-Type: application/json

{
    "text": "Test Editing",
    "description": "Testing Edit",
    "dueDate": "2023-03-01T23:59:59"
}
